'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class tabpage2

    '''<summary>
    '''lbl_Basket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Basket As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''btn_User1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_User1 As Global.DevExpress.Web.Bootstrap.BootstrapButton

    '''<summary>
    '''btn_User2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_User2 As Global.DevExpress.Web.Bootstrap.BootstrapButton

    '''<summary>
    '''btn_PostData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_PostData As Global.DevExpress.Web.Bootstrap.BootstrapButton

    '''<summary>
    '''ASPxLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel1 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ds_air_operator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_air_operator As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ds_mo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_mo As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ds_manufacturer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_manufacturer As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''BootstrapPageControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BootstrapPageControl1 As Global.DevExpress.Web.Bootstrap.BootstrapPageControl

    '''<summary>
    '''ds_Maintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_Maintenance As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ds_contact_person control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_contact_person As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''bgv_Maintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bgv_Maintenance As Global.DevExpress.Web.Bootstrap.BootstrapGridView
End Class
